options:
  source_branch:
    type: string
    default: "lp:~marcoceppi/charmrunner/add-server"
    description: branch to pull charmrunner from
  port:
    type: int
    default: 8080
    description: listen port
