#!/bin/sh
set -eu

apt-get -qq install -y zip

install_latest_charmrunner() {
  local branch=`config-get source_branch`

  rm -Rf /tmp/charmrunner
  bzr branch $branch /tmp/charmrunner
  ( cd /tmp/charmrunner && python setup.py install )
}
install_latest_charmrunner 
