#!/bin/sh

set -e

mongo_host=`relation-get private-address`
mongo_port=`relation-get port`
mongo_port=${mongo_port:-27017}

if [ -z "$mongo_host" ]; then
  juju-log "Waiting for data on the wire"
  exit 0
fi

cat > .mongodb <<EOF
mongo_host=$mongo_host
mongo_port=$mongo_port
EOF

hooks/config-changed
