#!/bin/sh

set -e

mongo_host=`relation-get private-address`
mongo_port=`relation-get port`

if [ -z "$mongo_port" ]; then
  juju-log "Waiting for data on the wire"
  exit 0
fi

cat > .mongodb <<EOF
mongo_host=$mongo_host
mongo_port=$mongo_port
EOF

stop mongodb || true
apt-get -y remove mongodb

hooks/config-changed

# Restart wasn't actually working. Had to stop then start.
hooks/stop
hooks/start
