#!/bin/bash
set -eu

apt-get -qq install -y zip mongodb charm-tools

create_charmrunner_user() {
  juju-log "Adding system user: charmrunner"
  useradd -r -c "charmrunner" -d "/var/lib/charmrunner" -s "/bin/false" -U charmrunner
}

create_charm_repo() {
  for series in precise; do
    mkdir -p /var/lib/charmrunner/charms/$series
  done
  chmod -R a+r /var/lib/charmrunner
  chown -Rf charmrunner:nogroup /var/lib/charmrunner
}

populate_charm_repo() {
  # Charm getall doesn't really work well with series. So lets pretend there is only
  # one series for now.
  # Rummor has it that I'm going to make getall multithreaded since it no longer
  # depends on mr. This process will soon hopefully not be so painful
  charm getall /var/lib/charmrunner/charms/precise
}

add_misc_development_cruft() {
  easy_install pymongo
  easy_install mongoqueue
  easy_install werkzeug

  #TODO maybe clean up requirements.txt instead?
  #apt-get -qq install -y python-pip build-essential python-dev
}

getent passwd charmrunner > /dev/null || create_charmrunner_user
create_charm_repo
populate_charm_repo
add_misc_development_cruft
